-- HSK 1–3 үгсийн монгол утга/жишээг байгалийн монгол болгосон засвар (408 мөр). Supabase SQL Editor дээр ажиллуулна.
begin;
update public.hsk_words set meaning_mn='-ийн; (хамаатуулах нөхцөл)', example_mn='Энэ миний ном.' where simplified='的' and hsk_level='1';
update public.hsk_words set meaning_mn='мөн, бол (холбох үйл үг)', example_mn='Тэр багш.' where simplified='是' and hsk_level='1';
update public.hsk_words set meaning_mn='байх, -тай байх', example_mn='Надад нэг ном бий.' where simplified='有' and hsk_level='1';
update public.hsk_words set meaning_mn='тэр (эр)', example_mn='Тэр миний найз.' where simplified='他' and hsk_level='1';
update public.hsk_words set meaning_mn='(ерөнхий тоолох үг)', example_mn='Нэг хүн.' where simplified='个' and hsk_level='1';
update public.hsk_words set meaning_mn='ба, болон; -тай', example_mn='би чи хоёр' where simplified='和' and hsk_level='1';
update public.hsk_words set meaning_mn='зөв; -руу', example_mn='Чи зөв хэлж байна.' where simplified='对' and hsk_level='1';
update public.hsk_words set meaning_mn='их, маш', example_mn='Би их баяртай байна.' where simplified='很' and hsk_level='1';
update public.hsk_words set meaning_mn='одоо болтол; бас', example_mn='Тэр одоо болтол ирээгүй байна.' where simplified='还' and hsk_level='1';
update public.hsk_words set meaning_mn='явах', example_mn='Би сургуульдаа явна.' where simplified='去' and hsk_level='1';
update public.hsk_words set meaning_mn='болох, болно', example_mn='Би орж болох уу?' where simplified='可以' and hsk_level='1';
update public.hsk_words set meaning_mn='том', example_mn='Энэ байшин том байна.' where simplified='大' and hsk_level='1';
update public.hsk_words set meaning_mn='доош; буух; дараагийн', example_mn='Бороо орлоо.' where simplified='下' and hsk_level='1';
update public.hsk_words set meaning_mn='жил', example_mn='Энэ жил 2026 он.' where simplified='年' and hsk_level='1';
update public.hsk_words set meaning_mn='олон, их', example_mn='Тэр олон номтой.' where simplified='多' and hsk_level='1';
update public.hsk_words set meaning_mn='хоёр', example_mn='Би хоёр хүүхэдтэй.' where simplified='两' and hsk_level='1';
update public.hsk_words set meaning_mn='дахин, дахиад', example_mn='Маргааш ярья.' where simplified='再' and hsk_level='1';
update public.hsk_words set meaning_mn='(асуултын аялга)', example_mn='Харин чи?' where simplified='呢' and hsk_level='1';
update public.hsk_words set meaning_mn='тэр (амьтан/эд юм)', example_mn='Энэ миний муур.' where simplified='它' and hsk_level='1';
update public.hsk_words set meaning_mn='шинэ', example_mn='Энэ миний шинэ утас.' where simplified='新' and hsk_level='1';
update public.hsk_words set meaning_mn='...гэж бодох/санах', example_mn='Надад энэ сайн санагдаж байна.' where simplified='觉得' and hsk_level='1';
update public.hsk_words set meaning_mn='машин, тэрэг', example_mn='Энэ миний машин.' where simplified='车' and hsk_level='1';
update public.hsk_words set meaning_mn='бүгд, бүгдээрээ', example_mn='Бүгдээрээ сайн уу!' where simplified='大家' and hsk_level='1';
update public.hsk_words set meaning_mn='маш, үнэхээр', example_mn='Энэ хоол маш амттай.' where simplified='非常' and hsk_level='1';
update public.hsk_words set meaning_mn='хүүхэд', example_mn='Тэр хоёр хүүхэдтэй.' where simplified='孩子' and hsk_level='1';
update public.hsk_words set meaning_mn='юм, эд зүйл', example_mn='Би юм авах гэж байна.' where simplified='东西' and hsk_level='1';
update public.hsk_words set meaning_mn='өдөр (огноо); дугаар', example_mn='Өнөөдөр сарын тав.' where simplified='号' and hsk_level='1';
update public.hsk_words set meaning_mn='найз', example_mn='Тэр миний сайн найз.' where simplified='朋友' and hsk_level='1';
update public.hsk_words set meaning_mn='тэдгээр', example_mn='Тэр хүмүүс оюутнууд.' where simplified='那些' and hsk_level='1';
update public.hsk_words set meaning_mn='утас (яриа)', example_mn='Надад утасдаарай.' where simplified='电话' and hsk_level='1';
update public.hsk_words set meaning_mn='эмэгтэй', example_mn='Тэр миний охин.' where simplified='女' and hsk_level='1';
update public.hsk_words set meaning_mn='өдөр', example_mn='Өнөөдөр сарын арав.' where simplified='日' and hsk_level='1';
update public.hsk_words set meaning_mn='яг ...ж байх', example_mn='Би хоол идэж байна.' where simplified='正在' and hsk_level='1';
update public.hsk_words set meaning_mn='(олон тоо заах нөхцөл)', example_mn='Сурагчид аа, сайн уу!' where simplified='们' and hsk_level='1';
update public.hsk_words set meaning_mn='юань (ярианы хэлэнд); хэсэг', example_mn='Энэ гурван юань.' where simplified='块' and hsk_level='1';
update public.hsk_words set meaning_mn='хэд, хэдэн', example_mn='Энэ ямар үнэтэй вэ?' where simplified='多少' and hsk_level='1';
update public.hsk_words set meaning_mn='ном', example_mn='Би ном унших дуртай.' where simplified='书' and hsk_level='1';
update public.hsk_words set meaning_mn='ноён, гуай', example_mn='Ван гуай байна уу?' where simplified='先生' and hsk_level='1';
update public.hsk_words set meaning_mn='эрэгтэй', example_mn='Тэр эрэгтэй хүүхэд.' where simplified='男' and hsk_level='1';
update public.hsk_words set meaning_mn='хоёр', example_mn='Хоёр дээр хоёрыг нэмбэл дөрөв.' where simplified='二' and hsk_level='1';
update public.hsk_words set meaning_mn='дэлгүүр, лангуу', example_mn='Урд нэг дэлгүүр байна.' where simplified='店' and hsk_level='1';
update public.hsk_words set meaning_mn='үдээс хойш', example_mn='Үдээс хойш би хичээлтэй.' where simplified='下午' and hsk_level='1';
update public.hsk_words set meaning_mn='тэдгээр (эд юм/амьтан)', example_mn='Энэ миний муурнууд.' where simplified='它们' and hsk_level='1';
update public.hsk_words set meaning_mn='гар утас', example_mn='Утасны цэнэг дууслаа.' where simplified='手机' and hsk_level='1';
update public.hsk_words set meaning_mn='охин', example_mn='Тэр нэг охинтой.' where simplified='女儿' and hsk_level='1';
update public.hsk_words set meaning_mn='гоё, үзэсгэлэнтэй', example_mn='Энэ хувцас гоё байна.' where simplified='漂亮' and hsk_level='1';
update public.hsk_words set meaning_mn='компьютер', example_mn='Энэ миний компьютер.' where simplified='电脑' and hsk_level='1';
update public.hsk_words set meaning_mn='утсаар ярих', example_mn='Би ээждээ утасдана.' where simplified='打电话' and hsk_level='1';
update public.hsk_words set meaning_mn='хичээл', example_mn='Өнөөдөр би гурван хичээлтэй.' where simplified='课' and hsk_level='1';
update public.hsk_words set meaning_mn='хоол, будаа', example_mn='Бид хамт хооллоно.' where simplified='饭' and hsk_level='1';
update public.hsk_words set meaning_mn='ангийн найз, ангийнхан', example_mn='Тэр миний ангийн найз.' where simplified='同学' and hsk_level='1';
update public.hsk_words set meaning_mn='сайхан харагдах, гоё', example_mn='Энэ хувцас гоё байна.' where simplified='好看' and hsk_level='1';
update public.hsk_words set meaning_mn='эмэгтэй дүү', example_mn='Манай дүү хөөрхөн.' where simplified='妹妹' and hsk_level='1';
update public.hsk_words set meaning_mn='үдээс өмнө', example_mn='Үдээс өмнө би хуралтай.' where simplified='上午' and hsk_level='1';
update public.hsk_words set meaning_mn='тэр тал, тэнд', example_mn='Дэлгүүр тэр талд байна.' where simplified='那边' and hsk_level='1';
update public.hsk_words set meaning_mn='эрэгтэй дүү', example_mn='Манай дүү сургуульд сурдаг.' where simplified='弟弟' and hsk_level='1';
update public.hsk_words set meaning_mn='хаана', example_mn='Чи хаашаа явж байна?' where simplified='哪儿' and hsk_level='1';
update public.hsk_words set meaning_mn='энэ тал', example_mn='Наашаа ирээрэй.' where simplified='这边' and hsk_level='1';
update public.hsk_words set meaning_mn='дэлгүүр', example_mn='Би дэлгүүр орж юм авна.' where simplified='商店' and hsk_level='1';
update public.hsk_words set meaning_mn='зүгээр, хамаагүй', example_mn='Зүгээр ээ, санаа зовох хэрэггүй.' where simplified='没关系' and hsk_level='1';
update public.hsk_words set meaning_mn='тэг', example_mn='Одоо арван цаг таван минут.' where simplified='零' and hsk_level='1';
update public.hsk_words set meaning_mn='уучлаарай (асуухын өмнө)', example_mn='Уучлаарай, бие засах газар хаана байна вэ?' where simplified='请问' and hsk_level='1';
update public.hsk_words set meaning_mn='зоогийн газар, ресторан', example_mn='Бид ресторанд хооллоно.' where simplified='饭店' and hsk_level='1';
update public.hsk_words set meaning_mn='өвдөх', example_mn='Тэр өвдөөд ажилдаа ирээгүй.' where simplified='生病' and hsk_level='1';
update public.hsk_words set meaning_mn='сонсголонтой, сайхан', example_mn='Энэ дуу их сайхан.' where simplified='好听' and hsk_level='1';
update public.hsk_words set meaning_mn='супермаркет, томоохон дэлгүүр', example_mn='Би супермаркет орж хүнс авна.' where simplified='超市' and hsk_level='1';
update public.hsk_words set meaning_mn='хүүхэд (бага насны)', example_mn='Хүүхдүүд ээ, сайн уу!' where simplified='小朋友' and hsk_level='1';
update public.hsk_words set meaning_mn='хичээл тарах', example_mn='Хичээл тараад бид хоол идэхээр явна.' where simplified='下课' and hsk_level='1';
update public.hsk_words set meaning_mn='банш', example_mn='Цагаан сараар бид банш иддэг.' where simplified='饺子' and hsk_level='1';
update public.hsk_words set meaning_mn='хятад хэл', example_mn='Би хятад хэл сураад хоёр жил болж байна.' where simplified='汉语' and hsk_level='1';
update public.hsk_words set meaning_mn='бууз (хятад)', example_mn='Би бууз идэх дуртай.' where simplified='包子' and hsk_level='1';
update public.hsk_words set meaning_mn='зүгээр ээ, юу ч биш', example_mn='Зүгээр ээ!' where simplified='不客气' and hsk_level='1';
update public.hsk_words set meaning_mn='зүгээр, юу ч биш, завтай байх', example_mn='Зүгээр ээ, санаа зовох хэрэггүй.' where simplified='没事' and hsk_level='1';
update public.hsk_words set meaning_mn='тэр, тэр нэг', example_mn='Тэр хүн миний багш.' where simplified='那个' and hsk_level='1';
update public.hsk_words set meaning_mn='аль, аль нь', example_mn='Чи алинд нь дуртай вэ?' where simplified='哪个' and hsk_level='1';
update public.hsk_words set meaning_mn='энэ, энэ нэг', example_mn='Энэ миний ном.' where simplified='这个' and hsk_level='1';
update public.hsk_words set meaning_mn='даруй, шууд; л', example_mn='Би одоохон ирнэ.' where simplified='就' and hsk_level='2';
update public.hsk_words set meaning_mn='(үргэлжлэх байдлын нөхцөл)', example_mn='Тэр инээгээд хэллээ.' where simplified='着' and hsk_level='2';
update public.hsk_words set meaning_mn='зөвшөөрөх, болгох; өгөх', example_mn='Ээж намайг амар гэлээ.' where simplified='让' and hsk_level='2';
update public.hsk_words set meaning_mn='өөрөө', example_mn='Үүнийг би өөрөө хийсэн.' where simplified='自己' and hsk_level='2';
update public.hsk_words set meaning_mn='магадгүй; боломж', example_mn='Тэр ирэхгүй байх.' where simplified='可能' and hsk_level='2';
update public.hsk_words set meaning_mn='(дайвар нөхцөл, -аар); газар', example_mn='Тэр хичээнгүй сурдаг.' where simplified='地' and hsk_level='2';
update public.hsk_words set meaning_mn='тийм; тэгвэл', example_mn='Битгий тэгж яар.' where simplified='那么' and hsk_level='2';
update public.hsk_words set meaning_mn='хамт', example_mn='Хамтдаа хоол идье.' where simplified='一起' and hsk_level='2';
update public.hsk_words set meaning_mn='(хүн тоолох хүндэтгэлийн үг)', example_mn='Энэ багш их сайн.' where simplified='位' and hsk_level='2';
update public.hsk_words set meaning_mn='найдах, хүсэх', example_mn='Чамайг амжилтад хүрээсэй гэж найдаж байна.' where simplified='希望' and hsk_level='2';
update public.hsk_words set meaning_mn='гар', example_mn='Гараа өргөөрэй.' where simplified='手' and hsk_level='2';
update public.hsk_words set meaning_mn='битгий, бүү', example_mn='Битгий ярь.' where simplified='别' and hsk_level='2';
update public.hsk_words set meaning_mn='урт', example_mn='Энэ зам их урт.' where simplified='长' and hsk_level='2';
update public.hsk_words set meaning_mn='гарч ирэх', example_mn='Тэр өрөөнөөсөө гарч ирлээ.' where simplified='出来' and hsk_level='2';
update public.hsk_words set meaning_mn='хэрэг, явдал', example_mn='Надад хийх ажил их байна.' where simplified='事情' and hsk_level='2';
update public.hsk_words set meaning_mn='авах, барих', example_mn='Үүнийг барьж байгаарай.' where simplified='拿' and hsk_level='2';
update public.hsk_words set meaning_mn='яг (одоо ...ж байна), зөв', example_mn='Би яг одоо хоол идэж байна.' where simplified='正' and hsk_level='2';
update public.hsk_words set meaning_mn='бүр, тутам', example_mn='Би өдөр бүр сурдаг.' where simplified='每' and hsk_level='2';
update public.hsk_words set meaning_mn='өнгөрсөн; өнгөрөх', example_mn='Өнгөрсөн юмаа битгий бод.' where simplified='过去' and hsk_level='2';
update public.hsk_words set meaning_mn='өгөх, хүргэх; үдэх', example_mn='Би чамайг гэрт чинь хүргэж өгье.' where simplified='送' and hsk_level='2';
update public.hsk_words set meaning_mn='инээх', example_mn='Тэр инээлээ.' where simplified='笑' and hsk_level='2';
update public.hsk_words set meaning_mn='гайгүй, сайн', example_mn='Чи гайгүй сайн хийжээ.' where simplified='不错' and hsk_level='2';
update public.hsk_words set meaning_mn='зам', example_mn='Энэ зам их өргөн.' where simplified='路' and hsk_level='2';
update public.hsk_words set meaning_mn='цэцэг, зарцуулах', example_mn='Энэ цэцэг их гоё.' where simplified='花' and hsk_level='2';
update public.hsk_words set meaning_mn='хэдийгээр', example_mn='Ядарсан ч их баяртай байна.' where simplified='虽然' and hsk_level='2';
update public.hsk_words set meaning_mn='буцаж ирэх', example_mn='Тэр буцаж ирлээ.' where simplified='回来' and hsk_level='2';
update public.hsk_words set meaning_mn='буруу', example_mn='Чи буруу байна.' where simplified='错' and hsk_level='2';
update public.hsk_words set meaning_mn='гүйх', example_mn='Тэр их хурдан гүйдэг.' where simplified='跑' and hsk_level='2';
update public.hsk_words set meaning_mn='арван мянга, түм', example_mn='Энэ арван мянган юанийн үнэтэй.' where simplified='万' and hsk_level='2';
update public.hsk_words set meaning_mn='гоймон, тал, нүүр', example_mn='Би гоймон идэх дуртай.' where simplified='面' and hsk_level='2';
update public.hsk_words set meaning_mn='хол', example_mn='Сургууль эндээс их хол.' where simplified='远' and hsk_level='2';
update public.hsk_words set meaning_mn='дотор', example_mn='Цүнхэнд мөнгө байгаа.' where simplified='里面' and hsk_level='2';
update public.hsk_words set meaning_mn='наашаа ирэх', example_mn='Наашаа ирээрэй.' where simplified='过来' and hsk_level='2';
update public.hsk_words set meaning_mn='бие, эрүүл мэнд', example_mn='Биеэ анхаараарай.' where simplified='身体' and hsk_level='2';
update public.hsk_words set meaning_mn='тийм, тэгж', example_mn='Тэгж битгий хэл.' where simplified='那样' and hsk_level='2';
update public.hsk_words set meaning_mn='зүг, руу', example_mn='Чигээрээ урагшаа яв.' where simplified='往' and hsk_level='2';
update public.hsk_words set meaning_mn='давхар, барилга', example_mn='Би гуравдугаар давхарт байдаг.' where simplified='楼' and hsk_level='2';
update public.hsk_words set meaning_mn='нүд', example_mn='Тэр том нүдтэй.' where simplified='眼睛' and hsk_level='2';
update public.hsk_words set meaning_mn='доош явах, үргэлжлэх', example_mn='Цааш нь яриарай.' where simplified='下去' and hsk_level='2';
update public.hsk_words set meaning_mn='-аас (зай заана)', example_mn='Сургууль манай гэрээс холгүй.' where simplified='离' and hsk_level='2';
update public.hsk_words set meaning_mn='ор', example_mn='Миний ор их тухтай.' where simplified='床' and hsk_level='2';
update public.hsk_words set meaning_mn='утга, санаа', example_mn='Энэ үг ямар утгатай вэ?' where simplified='意思' and hsk_level='2';
update public.hsk_words set meaning_mn='мартах', example_mn='Би мөнгө авахаа мартчихжээ.' where simplified='忘' and hsk_level='2';
update public.hsk_words set meaning_mn='дасгал, спорт', example_mn='Өдөр бүр дасгал хийх нь биед сайн.' where simplified='运动' and hsk_level='2';
update public.hsk_words set meaning_mn='буцаж явах', example_mn='Би буцлаа.' where simplified='回去' and hsk_level='2';
update public.hsk_words set meaning_mn='эхнэр', example_mn='Энэ миний эхнэр.' where simplified='妻子' and hsk_level='2';
update public.hsk_words set meaning_mn='мах', example_mn='Би мах идэх тийм ч дургүй.' where simplified='肉' and hsk_level='2';
update public.hsk_words set meaning_mn='үзэг', example_mn='Надад нэг үзэг зээлээч.' where simplified='笔' and hsk_level='2';
update public.hsk_words set meaning_mn='зүүн', example_mn='Зүүн тийшээ яваарай.' where simplified='左' and hsk_level='2';
update public.hsk_words set meaning_mn='шувуу', example_mn='Модон дээр нэг шувуу сууж байна.' where simplified='鸟' and hsk_level='2';
update public.hsk_words set meaning_mn='орох (дотогш)', example_mn='Дотогшоо ороорой.' where simplified='进去' and hsk_level='2';
update public.hsk_words set meaning_mn='зочид буудал', example_mn='Бид зочид буудалд байрлаж байгаа.' where simplified='酒店' and hsk_level='2';
update public.hsk_words set meaning_mn='удаан', example_mn='Жаахан аажуу яриач.' where simplified='慢' and hsk_level='2';
update public.hsk_words set meaning_mn='шалгах, шалгалт өгөх', example_mn='Би их сургуулийн шалгалт өгнө.' where simplified='考' and hsk_level='2';
update public.hsk_words set meaning_mn='хэсэг зуур', example_mn='Жаахан хүлээгээрэй.' where simplified='一会儿' and hsk_level='2';
update public.hsk_words set meaning_mn='нисэх онгоцны буудал', example_mn='Би найзаа тосохоор онгоцны буудал явна.' where simplified='机场' and hsk_level='2';
update public.hsk_words set meaning_mn='тухтай, эвтэйхэн', example_mn='Энэ сандал их тухтай.' where simplified='舒服' and hsk_level='2';
update public.hsk_words set meaning_mn='эмээ (аавын ээж)', example_mn='Манай эмээ их сайхан сэтгэлтэй.' where simplified='奶奶' and hsk_level='2';
update public.hsk_words set meaning_mn='овог, овогтой байх', example_mn='Би Ван овогтой.' where simplified='姓' and hsk_level='2';
update public.hsk_words set meaning_mn='бүрхэг, үүлэрхэг', example_mn='Өнөөдөр бүрхэг байна.' where simplified='阴' and hsk_level='2';
update public.hsk_words set meaning_mn='хобби, сонирхол', example_mn='Миний хобби ном унших.' where simplified='爱好' and hsk_level='2';
update public.hsk_words set meaning_mn='нэвтрэх тасалбар', example_mn='Тасалбар нь хэд вэ?' where simplified='门票' and hsk_level='2';
update public.hsk_words set meaning_mn='бугуйн цаг', example_mn='Энэ бугуйн цаг их үнэтэй.' where simplified='手表' and hsk_level='2';
update public.hsk_words set meaning_mn='гадаад явах', example_mn='Тэр гадаадад сурмаар байна.' where simplified='出国' and hsk_level='2';
update public.hsk_words set meaning_mn='сонирхолгүй, уйтгартай', example_mn='Энэ кино уйтгартай.' where simplified='没意思' and hsk_level='2';
update public.hsk_words set meaning_mn='шинэ жил тэмдэглэх, цагаан сар өнгөрүүлэх', example_mn='Бид шинэ жилээр гэртээ харьдаг.' where simplified='过年' and hsk_level='2';
update public.hsk_words set meaning_mn='(идэвхгүй хэв -гдах), хөнжил', example_mn='Түүнийг багш нь загнасан.' where simplified='被' and hsk_level='3';
update public.hsk_words set meaning_mn='төлөө, болгох', example_mn='ард түмний төлөө үйлчлэх' where simplified='为' and hsk_level='3';
update public.hsk_words set meaning_mn='дунд, дотор', example_mn='миний сэтгэлд' where simplified='中' and hsk_level='3';
update public.hsk_words set meaning_mn='хэрэв', example_mn='Бороо орвол би явахгүй.' where simplified='如果' and hsk_level='3';
update public.hsk_words set meaning_mn='болох, гэхдээ', example_mn='Энэ хэргийг том ч гэж болно, жижиг ч гэж болно.' where simplified='可' and hsk_level='3';
update public.hsk_words set meaning_mn='ёстой, ээлж', example_mn='Чи амрах цаг боллоо.' where simplified='该' and hsk_level='3';
update public.hsk_words set meaning_mn='улам, бүр', example_mn='Өнөөдөр өчигдрөөс ч хүйтэн байна.' where simplified='更' and hsk_level='3';
update public.hsk_words set meaning_mn='сая, дөнгөж, л', example_mn='Тэр сая л ирлээ.' where simplified='才' and hsk_level='3';
update public.hsk_words set meaning_mn='төстэй, адилхан', example_mn='Тэр аавтайгаа адилхан.' where simplified='像' and hsk_level='3';
update public.hsk_words set meaning_mn='үзэх, бодох', example_mn='Би үүнийг зөв гэж бодож байна.' where simplified='认为' and hsk_level='3';
update public.hsk_words set meaning_mn='ёстой, хэрэгтэй', example_mn='Чи ус их уух хэрэгтэй.' where simplified='应该' and hsk_level='3';
update public.hsk_words set meaning_mn='авч явах, бүс', example_mn='Гарахдаа мөнгө авахаа битгий мартаарай.' where simplified='带' and hsk_level='3';
update public.hsk_words set meaning_mn='төрөл, зүйл, үр', example_mn='Энэ жимс их амттай.' where simplified='种' and hsk_level='3';
update public.hsk_words set meaning_mn='олж мэдэх, илрүүлэх', example_mn='Би нэг асуудал олж мэдлээ.' where simplified='发现' and hsk_level='3';
update public.hsk_words set meaning_mn='заавал, гарцаагүй', example_mn='Чи гарцаагүй амжилтад хүрнэ.' where simplified='一定' and hsk_level='3';
update public.hsk_words set meaning_mn='амьдрал, амьдрах', example_mn='Түүний амьдрал их энгийн.' where simplified='生活' and hsk_level='3';
update public.hsk_words set meaning_mn='байнга, шууд', example_mn='Тэр чамайг хүлээгээд л байсан.' where simplified='一直' and hsk_level='3';
update public.hsk_words set meaning_mn='зүгээр л, гэхдээ', example_mn='Би зүгээр л тоглоом хийсэн.' where simplified='只是' and hsk_level='3';
update public.hsk_words set meaning_mn='түүнчлэн, бас', example_mn='Тэр ухаантай, бас хичээнгүй.' where simplified='而且' and hsk_level='3';
update public.hsk_words set meaning_mn='заавал, ёстой', example_mn='Чи цагтаа ирэх ёстой.' where simplified='必须' and hsk_level='3';
update public.hsk_words set meaning_mn='газар, нутаг', example_mn='Энэ газар их сайхан.' where simplified='地方' and hsk_level='3';
update public.hsk_words set meaning_mn='дараа нь', example_mn='Эхлээд хоолоо ид, дараа нь амар.' where simplified='然后' and hsk_level='3';
update public.hsk_words set meaning_mn='санаа зовох', example_mn='Санаа зовох хэрэггүй, зүгээр.' where simplified='担心' and hsk_level='3';
update public.hsk_words set meaning_mn='эсвэл', example_mn='Чи ч болно, тэр ч болно.' where simplified='或' and hsk_level='3';
update public.hsk_words set meaning_mn='олж авах', example_mn='Тэр нэгдүгээр байр авлаа.' where simplified='得到' and hsk_level='3';
update public.hsk_words set meaning_mn='улс орон', example_mn='Хятад том улс.' where simplified='国家' and hsk_level='3';
update public.hsk_words set meaning_mn='аюулгүй, аюулгүй байдал', example_mn='Болгоомжтой байгаарай.' where simplified='安全' and hsk_level='3';
update public.hsk_words set meaning_mn='сонгох, сонголт', example_mn='Чи дуртайгаа сонгож болно.' where simplified='选择' and hsk_level='3';
update public.hsk_words set meaning_mn='зөвхөн ... л', example_mn='Хичээж байж л амжилтад хүрнэ.' where simplified='只有' and hsk_level='3';
update public.hsk_words set meaning_mn='эсвэл', example_mn='Цай ч болно, кофе ч болно.' where simplified='或者' and hsk_level='3';
update public.hsk_words set meaning_mn='эмэгтэй хүн', example_mn='Тэр хатуужилтай эмэгтэй.' where simplified='女人' and hsk_level='3';
update public.hsk_words set meaning_mn='боломж, завшаан', example_mn='Энэ сайхан боломж.' where simplified='机会' and hsk_level='3';
update public.hsk_words set meaning_mn='хүртэх, тусах', example_mn='Тэр бэртчихсэн.' where simplified='受' and hsk_level='3';
update public.hsk_words set meaning_mn='бусад хүн, өөр хүн', example_mn='Бусад хүн юу гэж хэлэхийг битгий тоо.' where simplified='别人' and hsk_level='3';
update public.hsk_words set meaning_mn='илгээх, явуулах, ургах', example_mn='Би чамд мессеж явуулъя.' where simplified='发' and hsk_level='3';
update public.hsk_words set meaning_mn='захидал, итгэх', example_mn='Би түүнд захидал бичсэн.' where simplified='信' and hsk_level='3';
update public.hsk_words set meaning_mn='авах, тосох, залгах', example_mn='Би түүнийг онгоцны буудлаас тосно.' where simplified='接' and hsk_level='3';
update public.hsk_words set meaning_mn='сая, дөнгөж', example_mn='Тэр саяхан явлаа.' where simplified='刚' and hsk_level='3';
update public.hsk_words set meaning_mn='өөр, ялгаатай', example_mn='Бидний бодол өөр.' where simplified='不同' and hsk_level='3';
update public.hsk_words set meaning_mn='шийдэх', example_mn='Асуудлыг хамтдаа шийдье.' where simplified='解决' and hsk_level='3';
update public.hsk_words set meaning_mn='тухай', example_mn='Энэ түүхийн тухай ном.' where simplified='关于' and hsk_level='3';
update public.hsk_words set meaning_mn='дуусгах, гүйцэтгэх', example_mn='Би даалгавраа хийж дууслаа.' where simplified='完成' and hsk_level='3';
update public.hsk_words set meaning_mn='онцгой, ялангуяа', example_mn='Өнөөдөр ер бусын халуун байна.' where simplified='特别' and hsk_level='3';
update public.hsk_words set meaning_mn='анхаарах', example_mn='Болгоомжтой байгаарай.' where simplified='注意' and hsk_level='3';
update public.hsk_words set meaning_mn='орхих, явах', example_mn='Тэр гэрээсээ явчихсан.' where simplified='离开' and hsk_level='3';
update public.hsk_words set meaning_mn='улам (越...越...)', example_mn='Сурах тусам сонирхолтой.' where simplified='越' and hsk_level='3';
update public.hsk_words set meaning_mn='дуу, чимээ', example_mn='Жаахан чанга ярь.' where simplified='声' and hsk_level='3';
update public.hsk_words set meaning_mn='хот', example_mn='Бээжин том хот.' where simplified='城市' and hsk_level='3';
update public.hsk_words set meaning_mn='морь', example_mn='Тэр морь унаж байна.' where simplified='马' and hsk_level='3';
update public.hsk_words set meaning_mn='хүү, (нэр үгийн дагавар)', example_mn='Энэ миний хүү.' where simplified='子' and hsk_level='3';
update public.hsk_words set meaning_mn='нүүр', example_mn='Түүний нүүр улайлаа.' where simplified='脸' and hsk_level='3';
update public.hsk_words set meaning_mn='гэнэт', example_mn='Тэр гэнэт уйлчихлаа.' where simplified='突然' and hsk_level='3';
update public.hsk_words set meaning_mn='шалгах, үзлэг', example_mn='Эмч миний биеийг үзлээ.' where simplified='检查' and hsk_level='3';
update public.hsk_words set meaning_mn='хийх, зохицуулах', example_mn='Энэ асуудлыг шийдэхэд хэцүү.' where simplified='办' and hsk_level='3';
update public.hsk_words set meaning_mn='үндэслэн, дагуу', example_mn='Цаг агаарын мэдээгээр маргааш бороо орно.' where simplified='根据' and hsk_level='3';
update public.hsk_words set meaning_mn='саяхан, дөнгөж', example_mn='Тэр сая л гараад явлаа.' where simplified='刚刚' and hsk_level='3';
update public.hsk_words set meaning_mn='энгийн, хялбар', example_mn='Энэ асуулт их амархан.' where simplified='简单' and hsk_level='3';
update public.hsk_words set meaning_mn='юм шиг санагдах', example_mn='Тэр өвдсөн бололтой.' where simplified='好像' and hsk_level='3';
update public.hsk_words set meaning_mn='хүсэх, бэлэн байх', example_mn='Би чамд туслахад бэлэн.' where simplified='愿意' and hsk_level='3';
update public.hsk_words set meaning_mn='тууштай байх, зүтгэх', example_mn='Тэвчээр бол ялалт.' where simplified='坚持' and hsk_level='3';
update public.hsk_words set meaning_mn='харахад, бололтой', example_mn='Тэр ирэхгүй бололтой.' where simplified='看来' and hsk_level='3';
update public.hsk_words set meaning_mn='угтах, тавтай морил', example_mn='Манайд тавтай морил.' where simplified='欢迎' and hsk_level='3';
update public.hsk_words set meaning_mn='яаж, ямар', example_mn='Чи юу гэж бодож байна?' where simplified='怎样' and hsk_level='3';
update public.hsk_words set meaning_mn='авах, хүлээж авах', example_mn='Би захидлыг чинь авлаа.' where simplified='收' and hsk_level='3';
update public.hsk_words set meaning_mn='дуу хоолой', example_mn='Түүний хоолой их сайхан.' where simplified='声音' and hsk_level='3';
update public.hsk_words set meaning_mn='одоохон, тэр даруй', example_mn='Би одоохон очно.' where simplified='马上' and hsk_level='3';
update public.hsk_words set meaning_mn='болж хувирах', example_mn='Ус мөс болчихлоо.' where simplified='变成' and hsk_level='3';
update public.hsk_words set meaning_mn='зөвхөн ... л чадна', example_mn='Би түүнийг хүлээхээс өөр аргагүй.' where simplified='只能' and hsk_level='3';
update public.hsk_words set meaning_mn='уйлах', example_mn='Хүүхэд уйлчихлаа.' where simplified='哭' and hsk_level='3';
update public.hsk_words set meaning_mn='машин', example_mn='Тэр машин авлаа.' where simplified='汽车' and hsk_level='3';
update public.hsk_words set meaning_mn='хурал', example_mn='Үдээс хойш хурал бий.' where simplified='会议' and hsk_level='3';
update public.hsk_words set meaning_mn='туршиж үзэх', example_mn='Чи нэг туршаад үз.' where simplified='试' and hsk_level='3';
update public.hsk_words set meaning_mn='муу, дутах, зөрөх', example_mn='Түүний дүн их муу.' where simplified='差' and hsk_level='3';
update public.hsk_words set meaning_mn='дэргэд', example_mn='Би чиний дэргэд байхыг хүсэж байна.' where simplified='身边' and hsk_level='3';
update public.hsk_words set meaning_mn='зөвшөөрөх', example_mn='Би чиний саналтай санал нэг байна.' where simplified='同意' and hsk_level='3';
update public.hsk_words set meaning_mn='бараг', example_mn='Би бараг л мартчихсан.' where simplified='几乎' and hsk_level='3';
update public.hsk_words set meaning_mn='шалгах, хайх', example_mn='Толь бичгээс нэг хараач.' where simplified='查' and hsk_level='3';
update public.hsk_words set meaning_mn='хэрэггүй', example_mn='Баярлах хэрэггүй ээ.' where simplified='不用' and hsk_level='3';
update public.hsk_words set meaning_mn='ойрхон, ойролцоо', example_mn='Ойрхон нэг супермаркет байгаа.' where simplified='附近' and hsk_level='3';
update public.hsk_words set meaning_mn='нухацтай, хичээнгүй', example_mn='Тэр хичээлдээ их нухацтай.' where simplified='认真' and hsk_level='3';
update public.hsk_words set meaning_mn='хөл', example_mn='Хөл минь их өвдөж байна.' where simplified='脚' and hsk_level='3';
update public.hsk_words set meaning_mn='цахилгаан, цэнэг', example_mn='Утасны цэнэг дууслаа.' where simplified='电' and hsk_level='3';
update public.hsk_words set meaning_mn='байшин, гэр', example_mn='Тэд байшин худалдаж авсан.' where simplified='房子' and hsk_level='3';
update public.hsk_words set meaning_mn='хот; зах', example_mn='Бээжин хот их том.' where simplified='市' and hsk_level='3';
update public.hsk_words set meaning_mn='жишээ нь', example_mn='Би спортод дуртай, жишээ нь гүйх.' where simplified='比如' and hsk_level='3';
update public.hsk_words set meaning_mn='ам', example_mn='Тэр амаа хамхилаа.' where simplified='嘴' and hsk_level='3';
update public.hsk_words set meaning_mn='залуу', example_mn='Тэр одоохондоо залуу.' where simplified='年轻' and hsk_level='3';
update public.hsk_words set meaning_mn='удаан (хугацаа)', example_mn='Удаан уулзаагүй шүү.' where simplified='久' and hsk_level='3';
update public.hsk_words set meaning_mn='тэмдэглэх, тогтоох, цээжлэх', example_mn='Утасны дугаарыг минь сайн тогтоож ав.' where simplified='记' and hsk_level='3';
update public.hsk_words set meaning_mn='анхаарах, анхаарал хандуулах; дагах (сошиал)', example_mn='Бүгд энэ асуудлыг их анхаарч байна.' where simplified='关注' and hsk_level='3';
update public.hsk_words set meaning_mn='тоглолт; тоглох', example_mn='Тэдний тоглолт үнэхээр гоё байлаа.' where simplified='表演' and hsk_level='3';
update public.hsk_words set meaning_mn='үхэр', example_mn='Тариачин хэдэн үхэр тэжээдэг.' where simplified='牛' and hsk_level='3';
update public.hsk_words set meaning_mn='сая, дөнгөж сая', example_mn='Сая хэн ирсэн бэ?' where simplified='刚才' and hsk_level='3';
update public.hsk_words set meaning_mn='салхи', example_mn='Өнөөдөр салхи их байна.' where simplified='风' and hsk_level='3';
update public.hsk_words set meaning_mn='ажлын өрөө, оффис', example_mn='Менежер оффисдоо байгаа.' where simplified='办公室' and hsk_level='3';
update public.hsk_words set meaning_mn='тусах, гэрэлтүүлэх; зураг авах', example_mn='Нар газар дэлхийг гийгүүлж байна.' where simplified='照' and hsk_level='3';
update public.hsk_words set meaning_mn='орчин, хүрээлэн буй орчин', example_mn='Эндхийн орчин их сайхан.' where simplified='环境' and hsk_level='3';
update public.hsk_words set meaning_mn='зүг чиг', example_mn='Бид буруу зүг рүү явчихжээ.' where simplified='方向' and hsk_level='3';
update public.hsk_words set meaning_mn='санаа тавих, анхаарал халамж тавих', example_mn='Санаа тавьсанд баярлалаа.' where simplified='关心' and hsk_level='3';
update public.hsk_words set meaning_mn='баяр; (хичээлийн цагийн тоолох үг)', example_mn='Өнөөдөр хоёр цаг хичээлтэй.' where simplified='节' and hsk_level='3';
update public.hsk_words set meaning_mn='давхар; үе', example_mn='Тэр тав давхарт амьдардаг.' where simplified='层' and hsk_level='3';
update public.hsk_words set meaning_mn='өвчтөн', example_mn='Эмч өвчтөнийг асарч байна.' where simplified='病人' and hsk_level='3';
update public.hsk_words set meaning_mn='дотроо, сэтгэлдээ', example_mn='Дотор минь их муухай байна.' where simplified='心里' and hsk_level='3';
update public.hsk_words set meaning_mn='хөл (гуя, шилбэ)', example_mn='Хөл минь их өвдөж байна.' where simplified='腿' and hsk_level='3';
update public.hsk_words set meaning_mn='нэг тал; -нгаа ... -нгаа (зэрэг хийх)', example_mn='Тэр алхангаа дуулж байна.' where simplified='一边' and hsk_level='3';
update public.hsk_words set meaning_mn='зуршил; дасах', example_mn='Би эрт босож дассан.' where simplified='习惯' and hsk_level='3';
update public.hsk_words set meaning_mn='амралтын өдөр', example_mn='Амралтын өдрөөр чи юу хийдэг вэ?' where simplified='周末' and hsk_level='3';
update public.hsk_words set meaning_mn='дуулсан, сонссон (гэнэ)', example_mn='Чамайг гэрлэх гэж байгаа гэж дуулсан шүү.' where simplified='听说' and hsk_level='3';
update public.hsk_words set meaning_mn='хүртэл', example_mn='Би түүнийг иртэл нь хүлээсэн.' where simplified='直到' and hsk_level='3';
update public.hsk_words set meaning_mn='ноос, үс; мао (мөнгөний нэгж)', example_mn='Энэ хувцас хонины ноосоор хийсэн.' where simplified='毛' and hsk_level='3';
update public.hsk_words set meaning_mn='мартах', example_mn='Би түүний нэрийг мартчихлаа.' where simplified='忘记' and hsk_level='3';
update public.hsk_words set meaning_mn='завь, хөлөг онгоц', example_mn='Бид завиар гол гатласан.' where simplified='船' and hsk_level='3';
update public.hsk_words set meaning_mn='тэжээх, өсгөх', example_mn='Тэр нохой тэжээдэг.' where simplified='养' and hsk_level='3';
update public.hsk_words set meaning_mn='удаа (эхнээс нь дуустал)', example_mn='Дахиад нэг хэлээч.' where simplified='遍' and hsk_level='3';
update public.hsk_words set meaning_mn='-х гэж байх, төлөвлөх, санаархах', example_mn='Чи хаашаа явах гэж байна?' where simplified='打算' and hsk_level='3';
update public.hsk_words set meaning_mn='өрөө, тасалгаа', example_mn='Энэ хурлын өрөө.' where simplified='室' and hsk_level='3';
update public.hsk_words set meaning_mn='маш, туйлын; туйл', example_mn='Эндхийн байгаль үнэхээр үзэсгэлэнтэй.' where simplified='极' and hsk_level='3';
update public.hsk_words set meaning_mn='бид (ярьж буй хүнийг оролцуулаад)', example_mn='Хоюулаа хамт явъя.' where simplified='咱们' and hsk_level='3';
update public.hsk_words set meaning_mn='яах вэ', example_mn='Мөнгө дууслаа, яах вэ?' where simplified='怎么办' and hsk_level='3';
update public.hsk_words set meaning_mn='амьтан', example_mn='Би бяцхан амьтдад дуртай.' where simplified='动物' and hsk_level='3';
update public.hsk_words set meaning_mn='мод', example_mn='Хаалганы урд нэг мод бий.' where simplified='树' and hsk_level='3';
update public.hsk_words set meaning_mn='зүүн', example_mn='Нар зүүнээс мандана.' where simplified='东' and hsk_level='3';
update public.hsk_words set meaning_mn='үс (толгойн)', example_mn='Тэр урт үстэй.' where simplified='头发' and hsk_level='3';
update public.hsk_words set meaning_mn='айх', example_mn='Битгий ай.' where simplified='害怕' and hsk_level='3';
update public.hsk_words set meaning_mn='ойролцоогоор, барагцаагаар; магадгүй', example_mn='Арваад хүн байх.' where simplified='大概' and hsk_level='3';
update public.hsk_words set meaning_mn='соёл', example_mn='Хятадын соёл их баялаг.' where simplified='文化' and hsk_level='3';
update public.hsk_words set meaning_mn='яаралтай; яарах', example_mn='Битгий яар, аажуухан.' where simplified='急' and hsk_level='3';
update public.hsk_words set meaning_mn='хачин, сонин', example_mn='Энэ хачин юм байна.' where simplified='奇怪' and hsk_level='3';
update public.hsk_words set meaning_mn='бэлэг', example_mn='Энэ чамд өгөх бэлэг.' where simplified='礼物' and hsk_level='3';
update public.hsk_words set meaning_mn='урд, өмнө зүг', example_mn='Тэр хотын урд хэсэгт амьдардаг.' where simplified='南' and hsk_level='3';
update public.hsk_words set meaning_mn='дээшлүүлэх, сайжруулах', example_mn='Би хятад хэлээ сайжруулмаар байна.' where simplified='提高' and hsk_level='3';
update public.hsk_words set meaning_mn='сэтгэл хангалуун', example_mn='Багш надад их сэтгэл хангалуун байгаа.' where simplified='满意' and hsk_level='3';
update public.hsk_words set meaning_mn='хуучин', example_mn='Энэ хувцас дэндүү хуучин байна.' where simplified='旧' and hsk_level='3';
update public.hsk_words set meaning_mn='жолооч', example_mn='Таксины жолооч их найрсаг байсан.' where simplified='司机' and hsk_level='3';
update public.hsk_words set meaning_mn='хойд, умард', example_mn='Тэр хойд нутгийнх.' where simplified='北' and hsk_level='3';
update public.hsk_words set meaning_mn='олон, их', example_mn='Өнөөдөр маш олон хүн ирлээ.' where simplified='好多' and hsk_level='3';
update public.hsk_words set meaning_mn='сонирхол', example_mn='Би хөгжим их сонирхдог.' where simplified='兴趣' and hsk_level='3';
update public.hsk_words set meaning_mn='дүн, амжилт', example_mn='Тэр сайн дүнтэй.' where simplified='成绩' and hsk_level='3';
update public.hsk_words set meaning_mn='дунд, гол', example_mn='Тэр голд нь сууж байна.' where simplified='中间' and hsk_level='3';
update public.hsk_words set meaning_mn='охин (сурагч, оюутан)', example_mn='Манай ангид охид олон.' where simplified='女生' and hsk_level='3';
update public.hsk_words set meaning_mn='ухаантай', example_mn='Энэ хүүхэд их ухаантай.' where simplified='聪明' and hsk_level='3';
update public.hsk_words set meaning_mn='хэл', example_mn='Хятад хэл хэцүү хэл шүү.' where simplified='语言' and hsk_level='3';
update public.hsk_words set meaning_mn='вэбсайт', example_mn='Энэ вэбсайт их хэрэгтэй.' where simplified='网站' and hsk_level='3';
update public.hsk_words set meaning_mn='нар', example_mn='Өнөөдөр нар их ширүүн байна.' where simplified='太阳' and hsk_level='3';
update public.hsk_words set meaning_mn='амар, тохиромжтой', example_mn='Метрогоор явахад амар.' where simplified='方便' and hsk_level='3';
update public.hsk_words set meaning_mn='бараг, ойролцоо; бараг адил', example_mn='Бид бараг чацуу.' where simplified='差不多' and hsk_level='3';
update public.hsk_words set meaning_mn='мөс', example_mn='Усанд мөс байна.' where simplified='冰' and hsk_level='3';
update public.hsk_words set meaning_mn='тохиромжтой', example_mn='Энэ хувцас яг таарч байна.' where simplified='合适' and hsk_level='3';
update public.hsk_words set meaning_mn='уурлах', example_mn='Тэр уурлачихлаа.' where simplified='生气' and hsk_level='3';
update public.hsk_words set meaning_mn='нэрсийн жагсаалт', example_mn='Чиний нэр жагсаалтад байгаа.' where simplified='名单' and hsk_level='3';
update public.hsk_words set meaning_mn='халуун дотно, найрсаг', example_mn='Тэр хүмүүст их дотно ханддаг.' where simplified='热情' and hsk_level='3';
update public.hsk_words set meaning_mn='хаа сайгүй, газар сайгүй', example_mn='Хаа сайгүй хүн.' where simplified='到处' and hsk_level='3';
update public.hsk_words set meaning_mn='(нөхцөл: ...бол, -вал)', example_mn='Цаг гарвал манайд ирээрэй.' where simplified='的话' and hsk_level='3';
update public.hsk_words set meaning_mn='гол', example_mn='Голд загас их байдаг.' where simplified='河' and hsk_level='3';
update public.hsk_words set meaning_mn='зөөх, нүүх', example_mn='Бид дараа сард нүүнэ.' where simplified='搬' and hsk_level='3';
update public.hsk_words set meaning_mn='дасгал хийх, сургуулилах', example_mn='Тэр өдөр бүр уран бичлэгээр хичээллэдэг.' where simplified='练' and hsk_level='3';
update public.hsk_words set meaning_mn='хөөрөлдөх, ярилцах', example_mn='Бид жаахан хөөрөлдлөө.' where simplified='聊' and hsk_level='3';
update public.hsk_words set meaning_mn='хамт ажилладаг хүн', example_mn='Тэр надтай хамт ажилладаг.' where simplified='同事' and hsk_level='3';
update public.hsk_words set meaning_mn='том хүн, насанд хүрэгчид', example_mn='Энэ том хүмүүсийн хэрэг.' where simplified='大人' and hsk_level='3';
update public.hsk_words set meaning_mn='булан, өнцөг; жяо (мөнгөний нэгж)', example_mn='ширээний булан' where simplified='角' and hsk_level='3';
update public.hsk_words set meaning_mn='өндөр настан, ахмад хүн', example_mn='Бид ахмад хүмүүсээ хүндлэх ёстой.' where simplified='老人' and hsk_level='3';
update public.hsk_words set meaning_mn='хуудас', example_mn='Аравдугаар хуудсыг нээгээрэй.' where simplified='页' and hsk_level='3';
update public.hsk_words set meaning_mn='цэвэрхэн', example_mn='Өрөө цэвэрхэн байна.' where simplified='干净' and hsk_level='3';
update public.hsk_words set meaning_mn='санаа амрах, санаа зоволтгүй байх', example_mn='Чи санаа зоволтгүй.' where simplified='放心' and hsk_level='3';
update public.hsk_words set meaning_mn='өвс', example_mn='Зүлгэн дээр цэцэг их байна.' where simplified='草' and hsk_level='3';
update public.hsk_words set meaning_mn='чихэрлэг, амтлаг', example_mn='Энэ тарвас их чихэрлэг.' where simplified='甜' and hsk_level='3';
update public.hsk_words set meaning_mn='чимээгүй, нам гүм, тайван', example_mn='Чимээгүй байгаарай!' where simplified='安静' and hsk_level='3';
update public.hsk_words set meaning_mn='шүд', example_mn='Шүд минь их өвдөж байна.' where simplified='牙' and hsk_level='3';
update public.hsk_words set meaning_mn='хонь', example_mn='Бэлчээрт хонь их байна.' where simplified='羊' and hsk_level='3';
update public.hsk_words set meaning_mn='даалгавар (гэрийн)', example_mn='Би даалгавраа хийж дууслаа.' where simplified='作业' and hsk_level='3';
update public.hsk_words set meaning_mn='туранхай', example_mn='Тэр их туранхай.' where simplified='瘦' and hsk_level='3';
update public.hsk_words set meaning_mn='шар айраг', example_mn='Тэр нэг шил шар айраг уусан.' where simplified='啤酒' and hsk_level='3';
update public.hsk_words set meaning_mn='шинэхэн', example_mn='Энэ жимс их шинэхэн байна.' where simplified='新鲜' and hsk_level='3';
update public.hsk_words set meaning_mn='гунигтай, сэтгэл зовох', example_mn='Энэ мэдээг сонсоод дотор минь их муухай байна.' where simplified='难过' and hsk_level='3';
update public.hsk_words set meaning_mn='удалгүй', example_mn='Тэр удахгүй буцаад ирнэ.' where simplified='不久' and hsk_level='3';
update public.hsk_words set meaning_mn='ердийн үед, ер нь', example_mn='Би ер нь их завгүй.' where simplified='平时' and hsk_level='3';
update public.hsk_words set meaning_mn='хүү (сурагч, оюутан)', example_mn='Хөвгүүд хөл бөмбөг тоглож байна.' where simplified='男生' and hsk_level='3';
update public.hsk_words set meaning_mn='ойлгох, мэдэх', example_mn='Тэр олон юм мэддэг.' where simplified='懂得' and hsk_level='3';
update public.hsk_words set meaning_mn='удаан хугацаа', example_mn='Бид уулзаагүй удлаа.' where simplified='好久' and hsk_level='3';
update public.hsk_words set meaning_mn='математик', example_mn='Би математикт тааруу.' where simplified='数学' and hsk_level='3';
update public.hsk_words set meaning_mn='угаах (шүд); сойзоор арчих', example_mn='Би өдөр бүр шүдээ угаадаг.' where simplified='刷' and hsk_level='3';
update public.hsk_words set meaning_mn='тамирчин', example_mn='Тэр тамирчин.' where simplified='运动员' and hsk_level='3';
update public.hsk_words set meaning_mn='эгч дүүс', example_mn='Тэд эгч дүү хоёр.' where simplified='姐妹' and hsk_level='3';
update public.hsk_words set meaning_mn='урд нутаг, өмнөд', example_mn='Урд нутагт халуун.' where simplified='南方' and hsk_level='3';
update public.hsk_words set meaning_mn='амтлах', example_mn='Энэ хоолыг амталж үзээч.' where simplified='尝' and hsk_level='3';
update public.hsk_words set meaning_mn='харилцан яриа; ярилцах', example_mn='Энэ нэг харилцан яриа.' where simplified='对话' and hsk_level='3';
update public.hsk_words set meaning_mn='хөрш', example_mn='Манай хөрш их найрсаг.' where simplified='邻居' and hsk_level='3';
update public.hsk_words set meaning_mn='сургуулийн захирал', example_mn='Захирал хурал дээр байгаа.' where simplified='校长' and hsk_level='3';
update public.hsk_words set meaning_mn='цэцэрлэг (цэцгийн)', example_mn='Тэднийд цэцэрлэг бий.' where simplified='花园' and hsk_level='3';
update public.hsk_words set meaning_mn='тааралдах', example_mn='Би замд түүнтэй таарсан.' where simplified='遇见' and hsk_level='3';
update public.hsk_words set meaning_mn='эхнэр нөхөр', example_mn='Тэд эхнэр нөхөр хоёр.' where simplified='夫妻' and hsk_level='3';
update public.hsk_words set meaning_mn='авга ах (аавын дүү)', example_mn='Энэ манай авга ах.' where simplified='叔叔' and hsk_level='3';
update public.hsk_words set meaning_mn='үдэшлэг', example_mn='Өнөө орой нэг үдэшлэг болно.' where simplified='晚会' and hsk_level='3';
update public.hsk_words set meaning_mn='оноо авах', example_mn='Тэр гурван оноо авлаа.' where simplified='得分' and hsk_level='3';
update public.hsk_words set meaning_mn='15 минут (цагийн дөрөвний нэг); сийлэх', example_mn='Одоо гурав цаг арван тав.' where simplified='刻' and hsk_level='3';
update public.hsk_words set meaning_mn='дасгал хийх, чийрэгжүүлэх', example_mn='Дасгал хөдөлгөөн хийх биед сайн.' where simplified='锻炼' and hsk_level='3';
update public.hsk_words set meaning_mn='алдартай хүн', example_mn='Тэр алдартай хүн.' where simplified='名人' and hsk_level='3';
update public.hsk_words set meaning_mn='цахилгаан шат', example_mn='Цахилгаан шат эвдэрчихсэн байна.' where simplified='电梯' and hsk_level='3';
update public.hsk_words set meaning_mn='салхилах; хусах', example_mn='Өнөөдөр салхи их байна.' where simplified='刮' and hsk_level='3';
update public.hsk_words set meaning_mn='намхан', example_mn='Тэр намхан.' where simplified='矮' and hsk_level='3';
update public.hsk_words set meaning_mn='шуудан, имэйл', example_mn='Би түүн рүү имэйл явуулсан.' where simplified='邮件' and hsk_level='3';
update public.hsk_words set meaning_mn='... төдийгүй, зөвхөн ... биш', example_mn='Тэр ухаантай төдийгүй хичээнгүй.' where simplified='不但' and hsk_level='3';
update public.hsk_words set meaning_mn='хөргөгч', example_mn='Хөргөгчинд сүү байгаа.' where simplified='冰箱' and hsk_level='3';
update public.hsk_words set meaning_mn='өрөө', example_mn='Өрөөнд дулаахан байна.' where simplified='屋子' and hsk_level='3';
update public.hsk_words set meaning_mn='сургуулийн хашаа, кампус', example_mn='Сургуулийн хашаа том.' where simplified='校园' and hsk_level='3';
update public.hsk_words set meaning_mn='нагац эгч; эгч (насаар ах эмэгтэйд хандах); асрагч', example_mn='Асрагч эгч хүүхэд харахаар ирлээ.' where simplified='阿姨' and hsk_level='3';
update public.hsk_words set meaning_mn='эхнэр/нөхөр', example_mn='Энэ миний хань.' where simplified='爱人' and hsk_level='3';
update public.hsk_words set meaning_mn='баруун; барууны орнууд', example_mn='Тэр барууны орноос ирсэн.' where simplified='西方' and hsk_level='3';
update public.hsk_words set meaning_mn='талбай (тоглоомын)', example_mn='Талбай дээр хүн их байна.' where simplified='球场' and hsk_level='3';
update public.hsk_words set meaning_mn='яарах, сандрах', example_mn='Битгий сандар, аажуухан хэл.' where simplified='着急' and hsk_level='3';
update public.hsk_words set meaning_mn='эмнэлэгт хэвтэх', example_mn='Тэр эмнэлэгт хэвтчихлээ.' where simplified='住院' and hsk_level='3';
update public.hsk_words set meaning_mn='жуулчин', example_mn='Энд жуулчин их байна.' where simplified='游客' and hsk_level='3';
update public.hsk_words set meaning_mn='сар (тэнгэрийн)', example_mn='Өнөө орой сар дүүрэн байна.' where simplified='月亮' and hsk_level='3';
update public.hsk_words set meaning_mn='хэрэгтэй', example_mn='Энэ ном их хэрэгтэй.' where simplified='有用' and hsk_level='3';
update public.hsk_words set meaning_mn='цэцэрлэг, хүрээлэн', example_mn='Бид амьтны хүрээлэн явъя.' where simplified='园' and hsk_level='3';
update public.hsk_words set meaning_mn='хойд (нутаг)', example_mn='Хойд нутагт өвөл хүйтэн.' where simplified='北方' and hsk_level='3';
update public.hsk_words set meaning_mn='ачаа тээш', example_mn='Миний ачаа их хүнд.' where simplified='行李' and hsk_level='3';
update public.hsk_words set meaning_mn='цамц', example_mn='Тэр цагаан цамц өмссөн байна.' where simplified='衬衫' and hsk_level='3';
update public.hsk_words set meaning_mn='зам, гудамж', example_mn='Зам гарахдаа болгоомжтой байгаарай.' where simplified='马路' and hsk_level='3';
update public.hsk_words set meaning_mn='зүүн зүг, дорно; Дорнод', example_mn='Нар зүүнээс мандана.' where simplified='东方' and hsk_level='3';
update public.hsk_words set meaning_mn='түгээмэл, элбэг тохиолддог', example_mn='Энэ түгээмэл асуудал.' where simplified='常见' and hsk_level='3';
update public.hsk_words set meaning_mn='шат (барилгын)', example_mn='Тэр шатаар бууж ирлээ.' where simplified='楼梯' and hsk_level='3';
update public.hsk_words set meaning_mn='биеийн өндөр', example_mn='Тэр нэг наян өндөр.' where simplified='身高' and hsk_level='3';
update public.hsk_words set meaning_mn='даашинз, банзал', example_mn='Энэ даашинз их гоё.' where simplified='裙子' and hsk_level='3';
update public.hsk_words set meaning_mn='халуурах', example_mn='Хүүхэд халуурчихлаа.' where simplified='发烧' and hsk_level='3';
update public.hsk_words set meaning_mn='авдар, чемодан', example_mn='Энэ чемодан их хүнд.' where simplified='箱子' and hsk_level='3';
update public.hsk_words set meaning_mn='хүндрэлтэй асуудал', example_mn='Энэ хэцүү асуудал.' where simplified='难题' and hsk_level='3';
update public.hsk_words set meaning_mn='шүхэр', example_mn='Бороо орж байна, шүхэр аваарай.' where simplified='伞' and hsk_level='3';
update public.hsk_words set meaning_mn='уулзвар', example_mn='Уулзвар дээр зүүн тийш эргээрэй.' where simplified='路口' and hsk_level='3';
update public.hsk_words set meaning_mn='алдартай', example_mn='Тэр алдартай зураач.' where simplified='有名' and hsk_level='3';
update public.hsk_words set meaning_mn='зүүн хойд', example_mn='Тэр зүүн хойд нутгаас ирсэн.' where simplified='东北' and hsk_level='3';
update public.hsk_words set meaning_mn='шил, лонх', example_mn='Ширээн дээр нэг лонх байна.' where simplified='瓶子' and hsk_level='3';
update public.hsk_words set meaning_mn='намар', example_mn='Намар цаг агаар сайхан байдаг.' where simplified='秋天' and hsk_level='3';
update public.hsk_words set meaning_mn='гадаад паспорт', example_mn='Паспортоо авахаа битгий мартаарай.' where simplified='护照' and hsk_level='3';
update public.hsk_words set meaning_mn='хичээл тарах', example_mn='Хичээл тарсны дараа тоглоцгооё.' where simplified='放学' and hsk_level='3';
update public.hsk_words set meaning_mn='зураач', example_mn='Тэр алдартай зураач.' where simplified='画家' and hsk_level='3';
update public.hsk_words set meaning_mn='баруун урд', example_mn='Тэр баруун урд талд амьдардаг.' where simplified='西南' and hsk_level='3';
update public.hsk_words set meaning_mn='баруун хойд', example_mn='Баруун хойд нутаг хуурай уур амьсгалтай.' where simplified='西北' and hsk_level='3';
update public.hsk_words set meaning_mn='ариун цэврийн өрөө', example_mn='Ариун цэврийн өрөө хаана байна?' where simplified='卫生间' and hsk_level='3';
update public.hsk_words set meaning_mn='дээд хувцас, цамц', example_mn='Энэ цамц их гоё.' where simplified='上衣' and hsk_level='3';
update public.hsk_words set meaning_mn='өөр газар, орон нутаг', example_mn='Тэр орон нутгаас ирсэн.' where simplified='外地' and hsk_level='3';
update public.hsk_words set meaning_mn='амралт авах', example_mn='Тэр дараа долоо хоногт амралтаа авна.' where simplified='休假' and hsk_level='3';
update public.hsk_words set meaning_mn='хоцрох (тээвэр)', example_mn='Галт тэрэг хоцорчихлоо.' where simplified='晚点' and hsk_level='3';
update public.hsk_words set meaning_mn='амьтны хүрээлэн', example_mn='Бид хүүхдээ дагуулаад амьтны хүрээлэн явлаа.' where simplified='动物园' and hsk_level='3';
update public.hsk_words set meaning_mn='харандаа', example_mn='Надад харандаа нэг зээлээч.' where simplified='铅笔' and hsk_level='3';
update public.hsk_words set meaning_mn='түгээмэл хэрэглэгддэг', example_mn='Энэ түгээмэл хэрэглэдэг үг.' where simplified='常用' and hsk_level='3';
update public.hsk_words set meaning_mn='зочлох, дайлах', example_mn='Өнөөдөр би дайлна.' where simplified='请客' and hsk_level='3';
update public.hsk_words set meaning_mn='угаалгын машин', example_mn='Угаалгын машин эвдэрчихсэн.' where simplified='洗衣机' and hsk_level='3';
update public.hsk_words set meaning_mn='анги (хамт олон)', example_mn='Манай анги гучин хүнтэй.' where simplified='班级' and hsk_level='3';
update public.hsk_words set meaning_mn='муухай, муу харагдах', example_mn='Энэ хувцас муухай байна.' where simplified='难看' and hsk_level='3';
update public.hsk_words set meaning_mn='гадаад хэл', example_mn='Гадаад хэл сурах их хэрэгтэй.' where simplified='外语' and hsk_level='3';
update public.hsk_words set meaning_mn='сонирхох', example_mn='Би түүх сонирхдог.' where simplified='感兴趣' and hsk_level='3';
update public.hsk_words set meaning_mn='спортын наадам', example_mn='Сургууль спортын наадам зохион байгуулж байна.' where simplified='运动会' and hsk_level='3';
update public.hsk_words set meaning_mn='зочлох (айлд)', example_mn='Амралтын өдөр би найзындаа зочилно.' where simplified='做客' and hsk_level='3';
update public.hsk_words set meaning_mn='үсгийн толь', example_mn='Би толь бичгээс хайлаа.' where simplified='字典' and hsk_level='3';
update public.hsk_words set meaning_mn='ажлын өдөр', example_mn='Ажлын өдрүүдэд би их завгүй.' where simplified='工作日' and hsk_level='3';
update public.hsk_words set meaning_mn='хүргэлтийн хоол, захиалгын хоол', example_mn='Өнөөдөр хоол захиалъя.' where simplified='外卖' and hsk_level='3';
update public.hsk_words set meaning_mn='бэлэн гоймон', example_mn='Би бэлэн гоймон их иддэг.' where simplified='方便面' and hsk_level='3';
update public.hsk_words set meaning_mn='бадминтон', example_mn='Бид бадминтон тоглоё.' where simplified='羽毛球' and hsk_level='3';
update public.hsk_words set meaning_mn='чихэнд эвгүй', example_mn='Энэ дуу муухай сонсогдож байна.' where simplified='难听' and hsk_level='3';
update public.hsk_words set meaning_mn='сэрүүхэн', example_mn='Модны сүүдэрт сэрүүхэн.' where simplified='凉快' and hsk_level='3';
update public.hsk_words set meaning_mn='панда', example_mn='Панда их хөөрхөн.' where simplified='大熊猫' and hsk_level='3';
update public.hsk_words set meaning_mn='борооны цув', example_mn='Бороо орж байна, цуваа өмс.' where simplified='雨衣' and hsk_level='3';
update public.hsk_words set meaning_mn='гадаад оюутан', example_mn='Тэр гадаад оюутан.' where simplified='留学生' and hsk_level='3';
update public.hsk_words set meaning_mn='банкны карт', example_mn='Миний банкны карт алга боллоо.' where simplified='银行卡' and hsk_level='3';
update public.hsk_words set meaning_mn='тасалбар шалгах', example_mn='Тэрэгт суухын өмнө тасалбараа шалгуулна.' where simplified='检票' and hsk_level='3';
commit;
