/**
 * Display names for courses, independent of what the database happens to hold.
 *
 * Courses created by the ZIP importer get machine-written rows such as
 * `Auto-created from ZIP import (hsk2).`, and those strings were surfacing on
 * the learner home screen. Anything that looks machine-written is discarded in
 * favour of the canonical copy below.
 */

const AUTO_DESCRIPTION_PATTERNS = [
  /auto-?created/i,
  /zip import/i,
  /^untitled/i,
  /placeholder/i,
];

/** True when a database title/description is importer boilerplate. */
export function isAutoGeneratedCourseCopy(value: string | null | undefined) {
  const text = (value ?? "").trim();
  if (!text) return true;
  return AUTO_DESCRIPTION_PATTERNS.some((pattern) => pattern.test(text));
}

const HSK_LEVEL_TITLES: Record<string, string> = {
  hsk1: "HSK 1",
  hsk2: "HSK 2",
  hsk3: "HSK 3",
  hsk4: "HSK 4",
  hsk5: "HSK 5",
  hsk6: "HSK 6",
};

const HSK_LEVEL_SUBTITLES: Record<string, string> = {
  hsk1: "Анхан шат — дуудлага ба үндсэн өгүүлбэр",
  hsk2: "Анхан шат — өдөр тутмын яриа",
  hsk3: "Дунд шатны эхлэл",
  hsk4: "Дунд шат",
  hsk5: "Ахисан шат",
  hsk6: "Мэргэшсэн шат",
};

function normalizeCourseId(courseId: string): string {
  return courseId.trim().toLowerCase();
}

/** Canonical course name, falling back to the database title when usable. */
export function courseDisplayTitle(
  courseId: string,
  dbTitle?: string | null,
  fallback?: string
): string {
  const canonical = HSK_LEVEL_TITLES[normalizeCourseId(courseId)];
  if (canonical) return canonical;

  const text = (dbTitle ?? "").trim();
  if (text && !isAutoGeneratedCourseCopy(text)) return text;

  return fallback ?? courseId;
}

/** Canonical one-line course description, or "" when there is nothing to say. */
export function courseDisplaySubtitle(
  courseId: string,
  dbSubtitle?: string | null,
  fallback = ""
): string {
  const text = (dbSubtitle ?? "").trim();
  if (text && !isAutoGeneratedCourseCopy(text)) return text;

  return HSK_LEVEL_SUBTITLES[normalizeCourseId(courseId)] ?? fallback;
}
