-- Classroom schema PLAN — Buunduu Surtsgaay
-- Phase 7 Step 7: planning only. DO NOT run in production until reviewed.
-- No migration file in supabase/migrations/ yet — this documents future tables + RLS.

-- =============================================================================
-- teacher_profiles
-- Links auth.users to teacher-facing metadata (optional extension of profiles)
-- =============================================================================
-- Columns (planned):
--   id              uuid PRIMARY KEY DEFAULT gen_random_uuid()
--   user_id         uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE
--   display_name    text
--   organization    text
--   role            text NOT NULL DEFAULT 'teacher'  -- teacher | lead_teacher | admin_teacher
--   created_at      timestamptz DEFAULT now()
--   updated_at      timestamptz DEFAULT now()
--
-- RLS (planned):
--   SELECT/UPDATE/INSERT own row where auth.uid() = user_id
--   Admin read via existing admin_profiles pattern (if needed)

-- =============================================================================
-- classrooms
-- A class/group owned by a teacher
-- =============================================================================
-- Columns (planned):
--   id              uuid PRIMARY KEY DEFAULT gen_random_uuid()
--   teacher_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE
--   name            text NOT NULL
--   level           text  -- HSK5, Mixed, etc.
--   description     text
--   created_at      timestamptz DEFAULT now()
--   updated_at      timestamptz DEFAULT now()
--
-- RLS (planned):
--   Teacher: SELECT/INSERT/UPDATE/DELETE where auth.uid() = teacher_user_id
--   Student: SELECT where enrolled via classroom_students
--   Admin: SELECT for oversight (admin JWT + policy)

-- =============================================================================
-- classroom_students
-- Enrollment — student in a class (may be invite-by-email before signup)
-- =============================================================================
-- Columns (planned):
--   id              uuid PRIMARY KEY DEFAULT gen_random_uuid()
--   classroom_id    uuid NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE
--   student_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL  -- null until joined
--   display_name    text
--   email           text
--   invited_at      timestamptz DEFAULT now()
--   joined_at       timestamptz
--   UNIQUE (classroom_id, student_user_id) WHERE student_user_id IS NOT NULL
--   UNIQUE (classroom_id, email) WHERE email IS NOT NULL
--
-- RLS (planned):
--   Teacher: manage rows for own classrooms (via classrooms.teacher_user_id)
--   Student: SELECT own enrollment; UPDATE joined_at on self-join flow

-- =============================================================================
-- assignments
-- Teacher assigns lesson tasks to a class
-- =============================================================================
-- Columns (planned):
--   id              uuid PRIMARY KEY DEFAULT gen_random_uuid()
--   classroom_id    uuid NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE
--   lesson_id       text NOT NULL  -- matches public lesson id
--   assignment_type text NOT NULL  -- watch | vocabulary | quiz | review | full_lesson
--   instructions    text
--   due_date        date
--   status          text NOT NULL DEFAULT 'assigned'  -- assigned | archived
--   created_at      timestamptz DEFAULT now()
--   updated_at      timestamptz DEFAULT now()
--
-- RLS (planned):
--   Teacher: CRUD for assignments in own classrooms
--   Student: SELECT assignments for enrolled classrooms

-- =============================================================================
-- assignment_results
-- Per-student completion for an assignment
-- =============================================================================
-- Columns (planned):
--   id              uuid PRIMARY KEY DEFAULT gen_random_uuid()
--   assignment_id   uuid NOT NULL REFERENCES assignments(id) ON DELETE CASCADE
--   student_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE
--   status          text NOT NULL DEFAULT 'assigned'  -- assigned | in_progress | completed
--   completed_at    timestamptz
--   quiz_score      numeric(5,2)
--   metadata        jsonb DEFAULT '{}'::jsonb  -- words_learned, watch_progress, etc.
--   UNIQUE (assignment_id, student_user_id)
--
-- RLS (planned):
--   Teacher: SELECT/UPDATE for assignments in own classrooms
--   Student: SELECT/UPDATE own rows only (auth.uid() = student_user_id)

-- =============================================================================
-- Implementation notes (Phase 7 Step 8+)
-- =============================================================================
-- 1. Use anon client + RLS only — never service_role in Next.js app
-- 2. Teacher role: derive from teacher_profiles or classrooms.teacher_user_id
-- 3. Progress sync: link assignment_results to existing user_quiz_attempts / vocabulary progress
-- 4. Indexes: classroom_id, teacher_user_id, assignment_id, student_user_id
-- 5. Apply via supabase/migrations/011_classrooms.sql when ready

SELECT 'classroom_schema_plan.sql is planning-only — no tables created' AS notice;
