import type { LessonContent } from "@/types/lesson-content";

export const lesson3: LessonContent = {
  id: "3",
  courseId: "hsk5",
  title: "Lesson 3",
  chineseTitle: "我只是想照顾你",
  subtitle: "Халамжлах, санаа тавих, тайлбарлах үед хэрэглэгдэх өгүүлбэрүүд.",
  description:
    "Энэ хичээлээр халамжлах, санаа тавих, буруу ойлголцлоо тайлбарлах үед хэрэглэгдэх бодит хэллэгүүдийг сурна.",
  duration: "9 min",
  vocabularyCount: 12,
  quizCount: 5,
  status: "available",
  publishStatus: "available",
  videoPlaceholder: "Video lesson placeholder",
  watchTotalTime: "09:00",
  subtitlePreview: [
    {
      chinese: "我只是想照顾你。",
      pinyin: "Wǒ zhǐshì xiǎng zhàogù nǐ.",
      mongolian: "Би зүгээр л чамайг халамжлахыг хүссэн.",
    },
    {
      chinese: "可是你从来没有问过我想要什么。",
      pinyin: "Kěshì nǐ cónglái méiyǒu wèn guò wǒ xiǎng yào shénme.",
      mongolian:
        "Гэхдээ чи надаас юу хүсэж байгааг минь хэзээ ч асууж байгаагүй.",
    },
  ],
  timedSubtitles: [
    {
      start: "00:00",
      end: "00:03",
      chinese: "我只是想照顾你。",
      pinyin: "Wǒ zhǐshì xiǎng zhàogù nǐ.",
      mongolian: "Би зүгээр л чамайг халамжлахыг хүссэн.",
    },
    {
      start: "00:04",
      end: "00:07",
      chinese: "可是你从来没有问过我想要什么。",
      pinyin: "Kěshì nǐ cónglái méiyǒu wèn guò wǒ xiǎng yào shénme.",
      mongolian:
        "Гэхдээ чи надаас юу хүсэж байгааг минь хэзээ ч асууж байгаагүй.",
    },
    {
      start: "00:08",
      end: "00:11",
      chinese: "我以为你会喜欢。",
      pinyin: "Wǒ yǐwéi nǐ huì xǐhuan.",
      mongolian: "Чамд таалагдана гэж би бодсон.",
    },
    {
      start: "00:12",
      end: "00:15",
      chinese: "你以为的，不一定是我需要的。",
      pinyin: "Nǐ yǐwéi de, bù yídìng shì wǒ xūyào de.",
      mongolian: "Чиний бодсон зүйл заавал надад хэрэгтэй зүйл биш.",
    },
    {
      start: "00:16",
      end: "00:19",
      chinese: "那我以后会先问你。",
      pinyin: "Nà wǒ yǐhòu huì xiān wèn nǐ.",
      mongolian: "Тэгвэл би дараа нь эхлээд чамаас асууж байя.",
    },
    {
      start: "00:20",
      end: "00:23",
      chinese: "我需要的不是安排，而是尊重。",
      pinyin: "Wǒ xūyào de bú shì ānpái, ér shì zūnzhòng.",
      mongolian: "Надад хэрэгтэй зүйл бол зохицуулалт биш, харин хүндлэл.",
    },
  ],
  vocabulary: [
    {
      id: "zhishi",
      chinese: "只是",
      pinyin: "zhǐshì",
      mongolian: "зүгээр л, зөвхөн",
      hskLevel: "HSK4",
      exampleChinese: "我只是想照顾你。",
      exampleMongolian: "Би зүгээр л чамайг халамжлахыг хүссэн.",
    },
    {
      id: "zhaogu",
      chinese: "照顾",
      pinyin: "zhàogù",
      mongolian: "асрах, халамжлах",
      hskLevel: "HSK4",
      exampleChinese: "我只是想照顾你。",
      exampleMongolian: "Би зүгээр л чамайг халамжлахыг хүссэн.",
    },
    {
      id: "conglai",
      chinese: "从来",
      pinyin: "cónglái",
      mongolian: "ерөөсөө, хэзээ ч",
      hskLevel: "HSK5",
      exampleChinese: "你从来没有问过我。",
      exampleMongolian: "Чи надаас хэзээ ч асууж байгаагүй.",
    },
    {
      id: "wenguo",
      chinese: "问过",
      pinyin: "wèn guò",
      mongolian: "асууж байсан",
      hskLevel: "HSK4",
      exampleChinese: "你没有问过我想要什么。",
      exampleMongolian: "Чи миний юу хүсэж байгааг асууж байгаагүй.",
    },
    {
      id: "yiwei",
      chinese: "以为",
      pinyin: "yǐwéi",
      mongolian: "гэж бодох, андуурах",
      hskLevel: "HSK4",
      exampleChinese: "我以为你会喜欢。",
      exampleMongolian: "Чамд таалагдана гэж би бодсон.",
    },
    {
      id: "buyiding",
      chinese: "不一定",
      pinyin: "bù yídìng",
      mongolian: "заавал тийм биш",
      hskLevel: "HSK4",
      exampleChinese: "不一定是我需要的。",
      exampleMongolian: "Заавал миний хэрэгтэй зүйл биш.",
    },
    {
      id: "xuyao",
      chinese: "需要",
      pinyin: "xūyào",
      mongolian: "хэрэгтэй байх, хэрэгцээтэй",
      hskLevel: "HSK3",
      exampleChinese: "我需要的是尊重。",
      exampleMongolian: "Надад хэрэгтэй зүйл бол хүндлэл.",
    },
    {
      id: "yihou",
      chinese: "以后",
      pinyin: "yǐhòu",
      mongolian: "цаашдаа, дараа нь",
      hskLevel: "HSK3",
      exampleChinese: "我以后会先问你。",
      exampleMongolian: "Би цаашдаа эхлээд чамаас асууна.",
    },
    {
      id: "xian",
      chinese: "先",
      pinyin: "xiān",
      mongolian: "эхлээд, түрүүлж",
      hskLevel: "HSK3",
      exampleChinese: "我会先问你。",
      exampleMongolian: "Би эхлээд чамаас асууна.",
    },
    {
      id: "anpai",
      chinese: "安排",
      pinyin: "ānpái",
      mongolian: "зохицуулалт, төлөвлөх",
      hskLevel: "HSK4",
      exampleChinese: "我需要的不是安排。",
      exampleMongolian: "Надад хэрэгтэй зүйл зохицуулалт биш.",
    },
    {
      id: "ershi",
      chinese: "而是",
      pinyin: "ér shì",
      mongolian: "харин, харин бол",
      hskLevel: "HSK5",
      exampleChinese: "不是安排，而是尊重。",
      exampleMongolian: "Зохицуулалт биш, харин хүндлэл.",
    },
    {
      id: "zunzhong",
      chinese: "尊重",
      pinyin: "zūnzhòng",
      mongolian: "хүндлэх, хүндлэл",
      hskLevel: "HSK5",
      exampleChinese: "我需要的是尊重。",
      exampleMongolian: "Надад хэрэгтэй зүйл бол хүндлэл.",
    },
  ],
  quizQuestions: [
    {
      id: "q1",
      type: "multiple_choice",
      question: "“照顾” гэдэг үгийн зөв утга аль вэ?",
      options: ["асрах, халамжлах", "худалдаж авах", "явуулах", "мартах"],
      correctAnswer: "асрах, халамжлах",
      explanation:
        "“照顾” нь care for, look after буюу асрах, халамжлах гэсэн утгатай.",
    },
    {
      id: "q2",
      type: "multiple_choice",
      question: "“尊重” гэдэг үгийн зөв утга аль вэ?",
      options: ["хүндлэх, хүндлэл", "инээх", "асуух", "яарах"],
      correctAnswer: "хүндлэх, хүндлэл",
      explanation: "“尊重” нь respect буюу хүндлэл гэсэн утгатай.",
    },
    {
      id: "q3",
      type: "cloze",
      question: "我只是想____你。",
      options: ["照顾", "安排", "尊重", "从来"],
      correctAnswer: "照顾",
      explanation: "“我只是想照顾你。” = Би зүгээр л чамайг халамжлахыг хүссэн.",
    },
    {
      id: "q4",
      type: "cloze",
      question: "你____的，不一定是我需要的。",
      options: ["以为", "以后", "先", "只是"],
      correctAnswer: "以为",
      explanation:
        "“你以为的，不一定是我需要的。” = Чиний бодсон зүйл заавал надад хэрэгтэй зүйл биш.",
    },
    {
      id: "q5",
      type: "multiple_choice",
      question:
        "“我需要的不是安排，而是尊重。” өгүүлбэрийн хамгийн зөв Монгол утга аль вэ?",
      options: [
        "Надад хэрэгтэй зүйл бол зохицуулалт биш, харин хүндлэл.",
        "Би маргааш чамтай уулзана.",
        "Энэ хоол маш амттай байна.",
        "Чи надаас хэзээ ч асуугаагүй.",
      ],
      correctAnswer: "Надад хэрэгтэй зүйл бол зохицуулалт биш, харин хүндлэл.",
      explanation: "“不是……而是……” бүтэц нь “... биш, харин ...” гэсэн утгатай.",
    },
  ],
  quizTypes: [
    "Multiple choice",
    "Cloze blank",
    "Match Chinese to Mongolian",
  ],
};
