import type { LessonContent } from "@/types/lesson-content";

export const lesson2: LessonContent = {
  id: "2",
  courseId: "hsk5",
  title: "Lesson 2",
  chineseTitle: "你真的懂我吗？",
  subtitle: "Харилцаанд ойлголцол, асуулт, сэтгэл хөдлөлийн хэллэгүүд.",
  description:
    "Энэ хичээлээр харилцаанд хэрэглэгддэг асуулт, ойлголцол, мэдрэмж, тайлбарлах хэллэгүүдийг сурна.",
  duration: "7 min",
  vocabularyCount: 12,
  quizCount: 5,
  status: "available",
  publishStatus: "available",
  videoPlaceholder: "Video lesson placeholder",
  watchTotalTime: "07:00",
  subtitlePreview: [
    {
      chinese: "你真的懂我吗？",
      pinyin: "Nǐ zhēn de dǒng wǒ ma?",
      mongolian: "Чи намайг үнэхээр ойлгодог уу?",
    },
    {
      chinese: "我不是不在乎你。",
      pinyin: "Wǒ bú shì bù zàihū nǐ.",
      mongolian: "Би чамайг тоодоггүй гэсэн үг биш.",
    },
  ],
  timedSubtitles: [
    {
      start: "00:00",
      end: "00:03",
      chinese: "你真的懂我吗？",
      pinyin: "Nǐ zhēn de dǒng wǒ ma?",
      mongolian: "Чи намайг үнэхээр ойлгодог уу?",
    },
    {
      start: "00:04",
      end: "00:07",
      chinese: "我不是不在乎你。",
      pinyin: "Wǒ bú shì bù zàihū nǐ.",
      mongolian: "Би чамайг тоодоггүй гэсэн үг биш.",
    },
    {
      start: "00:08",
      end: "00:11",
      chinese: "只是有时候我不知道该怎么说。",
      pinyin: "Zhǐshì yǒu shíhou wǒ bù zhīdào gāi zěnme shuō.",
      mongolian: "Зүгээр л заримдаа би юу гэж хэлэхээ мэддэггүй.",
    },
    {
      start: "00:12",
      end: "00:15",
      chinese: "那你可以告诉我你的感受。",
      pinyin: "Nà nǐ kěyǐ gàosu wǒ nǐ de gǎnshòu.",
      mongolian: "Тэгвэл чи надад мэдрэмжээ хэлж болно шүү дээ.",
    },
    {
      start: "00:16",
      end: "00:19",
      chinese: "我怕说出来会让你难过。",
      pinyin: "Wǒ pà shuō chūlái huì ràng nǐ nánguò.",
      mongolian: "Хэлчихвэл чамайг гомдоочих вий гэж айсан.",
    },
    {
      start: "00:20",
      end: "00:23",
      chinese: "不说出来，我才更难过。",
      pinyin: "Bù shuō chūlái, wǒ cái gèng nánguò.",
      mongolian: "Хэлэхгүй байх чинь харин намайг илүү гомдоодог.",
    },
  ],
  vocabulary: [
    {
      id: "dong",
      chinese: "懂",
      pinyin: "dǒng",
      mongolian: "ойлгох",
      hskLevel: "HSK3",
      exampleChinese: "你真的懂我吗？",
      exampleMongolian: "Чи намайг үнэхээр ойлгодог уу?",
    },
    {
      id: "zaihu",
      chinese: "在乎",
      pinyin: "zàihū",
      mongolian: "тоох, санаа тавих",
      hskLevel: "HSK5",
      exampleChinese: "我不是不在乎你。",
      exampleMongolian: "Би чамайг тоодоггүй гэсэн үг биш.",
    },
    {
      id: "youshihou",
      chinese: "有时候",
      pinyin: "yǒu shíhou",
      mongolian: "заримдаа",
      hskLevel: "HSK3",
      exampleChinese: "有时候我不知道该怎么说。",
      exampleMongolian: "Заримдаа би юу гэж хэлэхээ мэддэггүй.",
    },
    {
      id: "gai",
      chinese: "该",
      pinyin: "gāi",
      mongolian: "ёстой, хэрэгтэй",
      hskLevel: "HSK4",
      exampleChinese: "我不知道该怎么说。",
      exampleMongolian: "Би яаж хэлэх ёстойгоо мэдэхгүй байна.",
    },
    {
      id: "gaosu",
      chinese: "告诉",
      pinyin: "gàosu",
      mongolian: "хэлэх, мэдэгдэх",
      hskLevel: "HSK3",
      exampleChinese: "你可以告诉我你的感受。",
      exampleMongolian: "Чи надад мэдрэмжээ хэлж болно.",
    },
    {
      id: "ganshou",
      chinese: "感受",
      pinyin: "gǎnshòu",
      mongolian: "мэдрэмж",
      hskLevel: "HSK5",
      exampleChinese: "告诉我你的感受。",
      exampleMongolian: "Надад мэдрэмжээ хэл.",
    },
    {
      id: "pa",
      chinese: "怕",
      pinyin: "pà",
      mongolian: "айх",
      hskLevel: "HSK3",
      exampleChinese: "我怕说出来会让你难过。",
      exampleMongolian: "Хэлчихвэл чамайг гомдоочих вий гэж айсан.",
    },
    {
      id: "shuochulai",
      chinese: "说出来",
      pinyin: "shuō chūlái",
      mongolian: "ам нээж хэлэх, ил хэлэх",
      hskLevel: "HSK4",
      exampleChinese: "不说出来，我才更难过。",
      exampleMongolian: "Хэлэхгүй байх чинь харин намайг илүү гомдоодог.",
    },
    {
      id: "rang",
      chinese: "让",
      pinyin: "ràng",
      mongolian: "хэн нэгнийг ямар нэг байдалд хүргэх",
      hskLevel: "HSK4",
      exampleChinese: "会让你难过。",
      exampleMongolian: "Чамайг гомдоох болно.",
    },
    {
      id: "nanguo",
      chinese: "难过",
      pinyin: "nánguò",
      mongolian: "гуниглах, сэтгэл өвдөх, гомдох",
      hskLevel: "HSK4",
      exampleChinese: "我才更难过。",
      exampleMongolian: "Би харин илүү гомдоно.",
    },
    {
      id: "cai",
      chinese: "才",
      pinyin: "cái",
      mongolian: "харин, сая, л",
      hskLevel: "HSK4",
      exampleChinese: "我才更难过。",
      exampleMongolian: "Би харин илүү гомдоно.",
    },
    {
      id: "geng",
      chinese: "更",
      pinyin: "gèng",
      mongolian: "илүү",
      hskLevel: "HSK3",
      exampleChinese: "我才更难过。",
      exampleMongolian: "Би харин илүү их гомдоно.",
    },
  ],
  quizQuestions: [
    {
      id: "q1",
      type: "multiple_choice",
      question: "“在乎” гэдэг үгийн зөв утга аль вэ?",
      options: ["тоох, санаа тавих", "хаалга нээх", "хоол хийх", "маргааш явах"],
      correctAnswer: "тоох, санаа тавих",
      explanation: "“在乎” нь care about буюу тоох, санаа тавих гэсэн утгатай.",
    },
    {
      id: "q2",
      type: "multiple_choice",
      question: "“难过” гэдэг үгийн зөв утга аль вэ?",
      options: ["гуниглах, гомдох", "баярлах", "худалдаж авах", "хурдан гүйх"],
      correctAnswer: "гуниглах, гомдох",
      explanation: "“难过” нь sad, upset гэсэн утгатай.",
    },
    {
      id: "q3",
      type: "cloze",
      question: "我不是不____你。",
      options: ["在乎", "难过", "告诉", "更"],
      correctAnswer: "在乎",
      explanation: "“我不是不在乎你。” = Би чамайг тоодоггүй гэсэн үг биш.",
    },
    {
      id: "q4",
      type: "cloze",
      question: "你可以____我你的感受。",
      options: ["告诉", "怕", "懂", "才"],
      correctAnswer: "告诉",
      explanation: "“你可以告诉我你的感受。” = Чи надад мэдрэмжээ хэлж болно.",
    },
    {
      id: "q5",
      type: "multiple_choice",
      question:
        "“我怕说出来会让你难过。” өгүүлбэрийн хамгийн зөв Монгол утга аль вэ?",
      options: [
        "Хэлчихвэл чамайг гомдоочих вий гэж айсан.",
        "Би одоо хоол хийж байна.",
        "Чи маргааш ирэх үү?",
        "Энэ үнэ хэтэрхий өндөр байна.",
      ],
      correctAnswer: "Хэлчихвэл чамайг гомдоочих вий гэж айсан.",
      explanation:
        "Энэ өгүүлбэрт “怕” = айх, “说出来” = ил хэлэх, “难过” = гомдох гэсэн утгатай.",
    },
  ],
  quizTypes: [
    "Multiple choice",
    "Cloze blank",
    "Match Chinese to Mongolian",
  ],
};
